### PR TITLE
revert stable documentation to match release 0.0.3-alpha-2

### LINKED ISSUE #51: Command errors in documentation
Documentation says :

> plm migration run

But this is not a [valid command](https://github.com/Plume-org/Plume/blob/0.3.0-alpha-2/plume-cli/src/main.rs) in 0.0.3-alpha-2 release.

See [this thread](https://toots.benpro.fr/@benoit/102359466236998527) for a real life exemple

### PR DESCRIPTION
**Pull request by trinity-1686a**
use diesel for migrations
fix #51

### CODE REVIEW

**Comment by igalic** [comment]
ooooor, we could make a new release

**Comment by elegaanz** [comment]
@igalic I don't know, there is not a lot of new things since the latest release…

**Review by elegaanz — APPROVED** [review]
This is another issue, but there are no links to latest.docs.joinplu.me anywhere, so it is almost impossible to discover…

**Comment by igalic** [comment]
@BaptisteGelez:
> I don't know, there is not a lot of new things since the latest release…

*mumbles something about "release early, release often"*

**Comment by elegaanz** [comment]
I was sure you would say that :smile: But you can't do a release if you don't have anything to release.

**Pull request merged**
